### PR TITLE
README added

### PR DESCRIPTION
**Pull request by RadoslawZerek**
Propozycja pliku README, nie wszystko jest opisane, jak macie jakieś pomysły to bardzo proszę :)

### CODE REVIEW

**Comment by nowy513** [comment]
do 6 dodałbym

**Comment by nowy513** [comment]
Cart can exist without a user,
Product and Group are disconnected, the product exists after the Group has been deleted,
Order is built on the basis of a Cart, it can exist without a user

Further development

Extension of user data in order to issue an invoice,
adding a method so that the user receives an email with information about the order after the transaction,

**Comment by MDi-1** [comment]
>
> Product and Group are disconnected, the product exists after the Group has been deleted,


Moim zdaniem to jest niepotrzebne. A w momencie gdy wykasujemy Cart albo Order pełen produktów to czy produkty znikną?

Dla mnie z grubsza jest ok

**Review by MDi-1 — APPROVED** [review]
Dla mnie z grubsza jest ok

**Pull request merged**
